language: python
python:
  - "2.6"
  - "2.7"
  # For now, Python 3 is not supported...
# command to install dependencies
install: "pip install -r dev_requirements.txt"
# command to run tests
script: "py.test"
