language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "pypy"

install: "pip install -r dev_requirements.txt"
script: "py.test"

# For now, Python 3 and pypy support is experimental.
matrix:
  allow_failures:
    - python: "3.3"
    - python: "pypy"

